name: Deploy # naming this workflow deploy

on: # on command is used to specify an event that will trigger the workflow, this event can be push, pull_request, etc.
  pull_request:
    branches:
      - miamistarter

env: # specify the environment variables for the deploy workflow
  NODE_VERSION: "14.x"

jobs:
  build-and-deploy: # specify the job we want to run, which in this case is a build job.
    runs-on: ubuntu-latest # specifying the OS you want your workflow to run on

    steps: # Steps indicate the various steps we want to run on a given job
      - uses: actions/checkout@v1 # use a predefined Github action for cloning the repo and checking into the  project directory.
        with:
          branch: miamistarter

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2 # use a predefined Github action to set up Node.js
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: yarn
        run: |
          yarn
      - name: yarn build
        run: |
          CI=false yarn build
      - name: yarn test
        run: |
          yarn test --passWithNoTests
